version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /platform/cli
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /siem-forwarder
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ssh-decoy
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /cti
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /dashboard
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /inference
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /siem-forwarder
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /adapters
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /http-decoy
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /platform/operator
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /adapters
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /platform/cli
    schedule:
      interval: monthly
