FROM golang:1.22-alpine@sha256:1699c10032ca2582ec89a24a1312d986a3f094aed3d5c1147b19880afe40e052 AS build
WORKDIR /src
COPY . .
RUN go mod tidy && go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /cicdecoy .

FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
RUN apk add --no-cache kubectl

# Non-root
RUN adduser -D -u 1000 cicdecoy
COPY --from=build /cicdecoy /usr/local/bin/cicdecoy

USER cicdecoy

ENTRYPOINT ["cicdecoy"]
